apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k3s-argocd-apps
  namespace: argocd
spec:
  # The project the application belongs to. We can group the applications with projects
  project: default
  sources:
    -  repoURL: https://github.com/spoved-aws/k3s-cluster.git
       targetRevision: HEAD
       path: .

  destination: 
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
